### ISSUE TITLE
Null symbols in key file after changing a password

### ISSUE THREAD

**Issue by vasiukoff** [cmason3/vaulty.go#1]
In case of changing password of keyfile null symblols appears on the beginiing of the file.
Example:
(NULL SYMBOLS HERE )// Public ID: vltys720...
If password changed more than one times, amount of null symbols is increased accordingly.

**Comment by cmason3** [comment]
Yep, I see what you mean.. it is probably down to the way I try and pre-allocate space for the destination slice to avoid Go over-sizing slices by doubling them.
