### ISSUE TITLE
Spaces in names of file(s)

### ISSUE THREAD

**Issue by vasiukoff** [cmason3/vaulty.go#2]
Vaulty will consider space symbol in file name as delimiter in the file list even if file name is in quotes or\and escaped by backslash symbol.

**Comment by cmason3** [comment]
What platform are you using as I can't recreate this problem under Linux?

```
$ go run vaulty.go encrypt "Argument 1" "Argument 2" "Argument 3"
Found Argument 1
Found Argument 2
Found Argument 3
```

**Comment by vasiukoff** [comment]
I've used compiled version of vaulty on Windows. Hmm, strage but after recompiling it works now. Closing as non exist error.
